pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                 sh '''
                   cd jenkins
                   chmod +x deploy.sh
                   ./deploy.sh
                    '''
            }
        }

        stage('Output'){
            steps {
                sh '''
                   cd jenkins
                   chmod +x output.sh
                   ./output.sh
                    '''
            }
        }

        stage('Ansible_run'){
            steps {
                sh '''
                   cd jenkins
                   chmod +x ansible.sh
                   ./ansible.sh
                    '''
            }
        }
    }

}

